// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: definition.proto

#include "definition.pb.h"
#include "definition.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace eventstream {

static const char* EventStream_method_names[] = {
  "/eventstream.EventStream/Listen",
};

std::unique_ptr< EventStream::Stub> EventStream::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< EventStream::Stub> stub(new EventStream::Stub(channel));
  return stub;
}

EventStream::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Listen_(EventStream_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::eventstream::Event>* EventStream::Stub::ListenRaw(::grpc::ClientContext* context, const ::eventstream::Auth& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::eventstream::Event>::Create(channel_.get(), rpcmethod_Listen_, context, request);
}

void EventStream::Stub::experimental_async::Listen(::grpc::ClientContext* context, ::eventstream::Auth* request, ::grpc::experimental::ClientReadReactor< ::eventstream::Event>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::eventstream::Event>::Create(stub_->channel_.get(), stub_->rpcmethod_Listen_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::eventstream::Event>* EventStream::Stub::AsyncListenRaw(::grpc::ClientContext* context, const ::eventstream::Auth& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::eventstream::Event>::Create(channel_.get(), cq, rpcmethod_Listen_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::eventstream::Event>* EventStream::Stub::PrepareAsyncListenRaw(::grpc::ClientContext* context, const ::eventstream::Auth& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::eventstream::Event>::Create(channel_.get(), cq, rpcmethod_Listen_, context, request, false, nullptr);
}

EventStream::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      EventStream_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< EventStream::Service, ::eventstream::Auth, ::eventstream::Event>(
          [](EventStream::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::eventstream::Auth* req,
             ::grpc_impl::ServerWriter<::eventstream::Event>* writer) {
               return service->Listen(ctx, req, writer);
             }, this)));
}

EventStream::Service::~Service() {
}

::grpc::Status EventStream::Service::Listen(::grpc::ServerContext* context, const ::eventstream::Auth* request, ::grpc::ServerWriter< ::eventstream::Event>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace eventstream

